import requests
import xml.etree.ElementTree as ET
import os
import re
from datetime import date, datetime, timedelta
import zipfile
import subprocess





URLS = {"sing_in": '/api/{2.6}/auth/signin',
        "sign_out": '/api/{2.6}/auth/signout',
        "publish workbook": '/api/{2.6}/sites/{site_id}/workbooks/{workbook_id}',
        "download workbook": '/api/{2.6}/sites/{site_id}/workbooks/{workbook_id}/content'}

AUTHENTICATION = {"sing_in":  '/api/{2.6}/auth/signin',
                  "sign_out": '/api/{2.6}/auth/signout'}
SITES = {"query": 'api/{2.6}/sites/{site_id}'}

PROJECTS = {"query": '/api/{2.6}/sites/{site_id}/projects'}

WORKBOOKS = {"query": '',
             "publish": '/api/{2.6}/sites/{site_id}/workbooks/{workbook_id}',
             "download": '/api/{2.6}/sites/{site_id}/workbooks/{workbook_id}/content'}


class AuthTokens:
    """storage class that holds (id,token) tuples"""

    LOGIN     = dict()
    LOGOUT    = dict()
    SITES     = dict()
    PROJECTS  = dict()
    WORKBOOKS = dict()


class TableauServerLogging:
    """memory class to store all logging information
    that is generated by the Tableau REST requests"""

    LOGGING = dict()

    def update_logging_data(*args, **kwargs):
        """add data to the logger"""
        temp_log_ = dict(*args, **kwargs)
        __class__.LOGGING.update(temp_log_)



class XmlBuilder(object):
    """xml builder class"""
    logger = TableauServerLogging()


    def __init__(self, url, version):
        self.sign_in_xml = None
        self.is_logged_in = False
        self.current_xml_request = None
        self.url_ = url.__str__()
        self.version_ = version.__str__()
        self.current_url_ = "http://{}/api/{}/auth/signin".format(self.url_, self.version_)
        self.xmlns = {'t': 'http://tableau.com/api'}

        self.server_response = None
        self.encoded_server_response = None
        self.status = None
        self.auth_token = None
        self.id = None
        self.uid = None
        self.temp_url = None
        self.project_information = None
        self.un = None
        self.pw = None

        # --- workbook data
        self.workbooks = list()

        # --- current workbook in processing
        self.WORKBOOK = None
        self.XML_WORKBOOK = None
        self.WORKBOOK_EXTRACTS = None



        # --- storage classes
        self.login = AuthTokens.LOGIN
        self.logout = AuthTokens.LOGOUT
        self.sites = AuthTokens.SITES
        self.projects = AuthTokens.PROJECTS
        self.workbooks = AuthTokens.WORKBOOKS


    def sign_in(self, un: str, pw: str, *args, **kwargs):
        """sign into the server"""
        signin_url = "http://{}/api/{}/auth/signin".format(self.url_, self.version_)
        #print("url {}".format(signin_url))
        xml_request = ET.Element('tsRequest')
        credentials = ET.SubElement(xml_request, 'credentials',
                                    name=un, password=pw)
        ET.SubElement(credentials, 'site', contentUrl='')
        self.sign_in_xml = ET.tostring(xml_request)
        try:
            # --- post a login request
            server_response = requests.post(signin_url, self.sign_in_xml)
            if server_response.status_code == 200:
                self.is_logged_in = True
                self.un = un
                self.pw = pw
                print("Login Successful: status:[{}]".format(server_response.status_code))

                # --- convert to a usable format for server
                text_response = server_response.text
                encoded_response = (str(text_response).encode('ascii', errors='backslashreplace').decode('utf-8'))
                parsed_response = ET.fromstring(encoded_response)

                # --- grab needed authorization tokens
                self.auth_token = parsed_response.find('t:credentials', namespaces=self.xmlns).get('token')
                self.id = parsed_response.find('.//t:site', namespaces=self.xmlns).get('id')
                self.uid = parsed_response.find('.//t:user', namespaces=self.xmlns).get('id')
                print(self.id)
                self.login.update({"id": id, "token": self.auth_token})
            else:
                raise Exception("Login Failed: status code: [{}]".format(server_response.status_code))
        except Exception as e:
            print(str(e))


    def sign_out(self, *args, **kwargs):
        """sign out of the server"""
        signout_url = "http://{}/api/{}/auth/signout".format(self.url_, self.version_)
        print(signout_url)
        # --- get auth token
        try:
            srvr_response = requests.post(signout_url,
                                          headers={'x-tableau-auth': self.auth_token})
            if srvr_response.status_code == 204:
                print("Logout Successful: status:[{}]".format(srvr_response.status_code))
                self.logout.update({"id": self.login.get("id"), "token": self.login.get("token")})
            else:
                raise Exception("Logout Failed: status:[{}]".format(srvr_response.status_code))
        except Exception as e:
            print(str(e))

    def query_workbooks(self, workbook_name):
        """returns workbook information"""

        workbook_url = "http://{}/api/{}/sites/{}/users/{}/workbooks".format(self.url_,
                                                                      self.version_,
                                                                      self.id,
                                                                      self.uid)
        server_response = requests.get(workbook_url, headers={'x-tableau-auth': self.auth_token})
        text_response = server_response.text
        encoded_response = (str(text_response).encode('ascii', errors='backslashreplace').decode('utf-8'))

        try:
            if server_response.status_code == 200:
                print("Connected to Workbooks: response[{}]".format(server_response.status_code))
                xml_response = ET.fromstring(encoded_response)
                all_workbooks = xml_response.findall('.//t:workbook', namespaces=self.xmlns)
                self.workbooks = {wb.get('name'): wb.get('id') for wb in all_workbooks}
                #for wb in self.workbooks:
                #    print(wb.get('name'), wb.get('id'))
            else:
                raise Exception("Error connecting to workbooks: response[{}]".format(server_response))
        except Exception as e:
            print(str(e))

    def download_workbook(self):
        """get workbook"""

        file_ = "GANTT_Test.twb" # --- to be removed

        workbook_url ="http://{}/api/{}/sites/{}/workbooks/{}/content".format(self.url_,
                                                                         self.version_,
                                                                         self.id,
                                                                         self.workbooks.get('GANTT_7_13_2017'))

        server_response = requests.get(workbook_url, headers={'x-tableau-auth': self.auth_token},
                                                     allow_redirects=True)
        if server_response.status_code == 200:
            os.mkdir("TABLEAU_TEMP_DIR")
            os.chdir(path="F:\\local-git\\TableauREST_API\\TABLEAU_TEMP_DIR")
            print("Download Status: [{}]\n\t proceeding with download ...".format(server_response.status_code))
            with open(file_, 'wb') as twbx:
                twbx.write(server_response.content)
            self.WORKBOOK = file_

    def open_workbook_xml(self):
        """check to see if tableau workbook is zipped"""
        if self.WORKBOOK is not None:
            if zipfile.is_zipfile(self.WORKBOOK):
                zip_file = zipfile.ZipFile(self.WORKBOOK)
                # --- set the workbook to the .twb file
                self.WORKBOOK = list(filter(lambda x: x.split('.')[-1] in ('twb', 'tds'),
                                              zip_file.namelist()))[0]
                print(self.WORKBOOK)
                #print("twbx archives: {}".format(archived_files))
                #self.WORKBOOK_EXTRACTS = zip_file.extract(*archived_files, 'F:\\local-git\\TableauREST_API')
                zip_file.extractall(path='F:\\local-git\\TableauREST_API\\TABLEAU_TEMP_DIR')
            else:
                # --- no zipfile process needed
                self.WORKBOOK_EXTRACTS = self.WORKBOOK
        else:
            print("No workbook downloaded...")

    def update_parameters(self, parameter_name: str, tag_name: str, save=False):
        """update specified workbook parameters"""
        self.XML_WORKBOOK = ET.parse(self.WORKBOOK)
        print(type(self.XML_WORKBOOK))

        root = self.XML_WORKBOOK.getroot()
        current_parameter = "'[{}]'".format(parameter_name)
        xml_search_query = ".//*[@name={}]/{}".format(current_parameter, tag_name)

        QUERY = root.find(xml_search_query)
        query_children = QUERY.getchildren()

        date_lambda = datetime.datetime.strptime((query_children[-1]
                                                  .attrib.get('value')
                                                  .strip('#')
                                                  .strip(' 00:00:00')),
                                                   "%Y-%m-%d")
        current_date = datetime.date.today()
        day_difference = int(str(datetime.date.today() - datetime.date(date_lambda.year,
                                                                       date_lambda.month,
                                                                       date_lambda.day)).split(" ")[0])
        print("CURRENT DATE: {}".format(current_date))
        print("Date Difference: {}".format(day_difference))


    def create_pdf(self):
        """create a pdf of the Daily/Weekly/Monthly Dashboards"""
        tabcmd = subprocess.check_output(['ls', '-l'])








    def query_projects(self):
        """returns a list of projects"""
        self.temp_url = "http://" + self.url_ + " /api/{}/sites/{}/projects".format(self.version_, self.id)
        paged_url = "http://" + self.url_ + "?pageSize={0}&pageNumber={1}".format(1, 100)
        print(paged_url)
        print(self.temp_url)
        srvr_response = requests.get(paged_url, headers={'x-tableau-auth': self.auth_token})
        text_resp = srvr_response.text

        #encoded_text_resp = str(text_resp).encode('ascii', errors="backslashreplace").decode('utf-8')
        #xml_resp = ET.fromstring(encoded_text_resp)
        #self.project_information = xml_resp









if __name__=="__main__":
    xml = XmlBuilder(url='172.31.32.54', version=2.6)
    #xml.build_xml(True, name='wmurphy', password='Tr2oy2222!')
    xml.sign_in(un='Administrator', pw='=%vT8AFMj$')
    xml.query_workbooks("Risk and Demographics")
    #xml.sign_out()

    #xml.make_request()
    #print(xml.status)
    #xml.get_token()
    #print(xml.auth_token)
    #print(xml.id)
    #xml.query_projects()

    xml.download_workbook()
    xml.open_workbook_xml()
    xml.create_pdf()
    #xml.update_parameters()
    #print(xml.workbooks)



    """
    def sign_out(self):
        self.temp_url = "http://" + self.url_ + "/api/{}/auth/signout".format(self.version_)
        srvr_response = requests.post(self.temp_url, headers={'x-tableau-auth': self.auth_token})
        self.status = srvr_response.status_code"""
